name: tests

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

      matrix:
        os: [ubuntu-latest]
        node: [12]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node }}
    - name: npm install, build, and test
      run: |
        npm i
        npm test
      env:
        CI: true
